### ISSUE TITLE
トップページの種目の並び順そろそろWCAにしてもいいかも

### ISSUE THREAD

**Issue by kotarot** [tribox/tribox-contest#101]
急に変えると混乱するとか考えてたけど、アイコンとかも導入して近いうちにWCA順に変えたい。

**Comment by kotarot** [comment]
Icon: https://github.com/tribox/tribox-contest/issues/98

**Comment by kotarot** [comment]
2020年前半期から変えたい。

**Comment by fumikikoseki** [comment]
トップページ、結果ページは片手→最少という表示順なのに、
マイページは最少→片手の表示順になっているのを直してほしい

**Comment by kotarot** [comment]
@fumikikoseki 確かにそうですね... 修正します！

**Comment by kotarot** [comment]
#130 で修正しました。2021H1シーズンから適用されます。
