### ISSUE TITLE
INVALID_USERのエラーメッセージが正しく表示されない

### ISSUE THREAD

**Issue by haseda** [tribox/tribox-contest#16]
エラーメッセージの代わりに、{"code":"INVALID_USER"}が表示されます。

https://github.com/tribox/tribox-contest/blob/e035bb646706207e828192c553f8d0e549826200/app/views/basejs.scala.html#L24
が表示されるべき？？

再現手順：
DBに存在しないアカウント(メールアドレス)でパスワードリセットをする

<img width="545" alt="screen shot 2016-11-08 at 11 14 30 pm" src="https://cloud.githubusercontent.com/assets/1887123/20102510/b1b43d56-a609-11e6-9a68-5ef0647b9227.png">

**Comment by kotarot** [comment]
@haseda 報告ありがとうございます。

> https://github.com/tribox/tribox-contest/blob/e035bb646706207e828192c553f8d0e549826200/app/views/basejs.scala.html#L24
> が表示されるべき？？

まったくその通りです。近日中に修正します。

**Comment by kotarot** [comment]
@haseda 修正しました。本番にも反映させています。チェックお願いします。

**Comment by haseda** [comment]
@kotarot LGTM！確認しました。
